const mongoose = require('mongoose');

const tennisPlayerSchema = new mongoose.Schema({
  playerId: {
    type: Number,
    required: true,
  },
  type: {
    type: String,
    enum: ['atp', 'wta'],
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  birthday: Date,
  countryAcr: String,
  height: Number,
  wikidata_id: String,
  currentRank: Number,
  progress: Number,
  points: Number,
  ch: Number,
  hardPoints: Number,
  hardTournament: Number,
  ihardPoints: Number,
  ihardTournament: Number,
  clayPoints: Number,
  clayTournament: Number,
  grassPoints: Number,
  grassTournament: Number,
  carpetPoints: Number,
  carterTournament: Number,
  doublesPosition: Number,
  doublesPoints: Number,
  doublesProgress: Number,
  prize: Number,
  itf: Number,
  ep: {
    turnedPro: String,
    plays: String,
    coach: String,
    birthplace: String,
    residence: String,
    weight: String,
    playerStatus: String,
    twitter: String,
    instagram: String,
    facebook: String,
    site: String,
    page: String,
    last_revised: String,
  },
  pastMatches: [{
    id: Number,
    date: Date,
    result: String,
    best_of: String,
    odd1: String,
    odd2: String,
    player1Id: Number,
    player2Id: Number,
    tournamentId: Number,
    roundId: Number,
    player1: {
      id: Number,
      name: String,
      countryAcr: String,
    },
    player2: {
      id: Number,
      name: String,
      countryAcr: String,
    },
    tournament: {
      id: Number,
      name: String,
      courtId: Number,
      rankId: Number,
    },
  }],
  matchStats: {
    serviceStats: {
      acesGm: Number,
      doubleFaultsGm: Number,
      firstServeGm: Number,
      firstServeOfGm: Number,
      winningOnFirstServeGm: Number,
      winningOnFirstServeOfGm: Number,
      winningOnSecondServeGm: Number,
      winningOnSecondServeOfGm: Number,
    },
    rtnStats: {
      acesGm: Number,
      doubleFaultsGm: Number,
      firstServeGm: Number,
      firstServeOfGm: Number,
      winningOnFirstServeGm: Number,
      winningOnFirstServeOfGm: Number,
      winningOnSecondServeGm: Number,
      winningOnSecondServeOfGm: Number,
    },
    breakPointsServeStats: {
      breakPointFacedGm: Number,
      breakPointSavedGm: Number,
    },
    breakPointsRtnStats: {
      breakPointChanceGm: Number,
      breakPointWonGm: Number,
    },
  },
  surfaceSummary: [{
    year: String,
    surfaces: [{
      courtId: Number,
      court: String,
      courtWins: String,
      courtLosses: String,
    }],
  }],
  titles: [{
    tourRankId: String,
    tourRank: String,
    titlesWon: String,
    titlesLost: String,
  }],
  finals: [{
    id: Number,
    date: Date,
    result: String,
    roundId: Number,
    player1: {
      id: Number,
      name: String,
      countryAcr: String,
    },
    player2: {
      id: Number,
      name: String,
      countryAcr: String,
    },
    tournament: {
      id: Number,
      name: String,
      prize: String,
    },
  }],
  tournamentRecords: [{
    year: Number,
    tournamentId: Number,
    tournamentName: String,
    bestRoundId: Number,
    bestRound: String,
    wins: Number,
    losses: Number,
  }],
  lastUpdated: {
    type: Date,
    default: Date.now,
  },
}, {
  timestamps: true,
});

module.exports = mongoose.model('TennisPlayer', tennisPlayerSchema);